name: Check Lint
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  lint:
    name: Check Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Poetry Setup
        uses: snok/install-poetry@v1
      - name: Checkout ScanAPI repository
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: poetry install
      - name: Run Lint Check
        id: lint
        run: |
          make check
        continue-on-error: true
      - name: Lint Failed
        if: steps.lint.outcome != 'success'
        run: |
          echo -e "\033[0;31m Please, run \`make format\` and push the changes to fix this error"
          exit 1
