name: Publish to Production
on:
  release:
    types: [published]
jobs:
  build-n-publish:
    name: Publish to PyPI. Build and publish Python 🐍 distributions 📦
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Poetry Setup
        uses: snok/install-poetry@v1
        with:
          version: 1.3.2
      - name: Build and publish to pypi
        run: |
          poetry build
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish
